### ISSUE TITLE
Build instructions fail. missing get-deps.sh README 

### ISSUE THREAD

**Issue by knitzsche** [canonical/iot-management#14]
$  go get github.com/canonical/iot-management
package github.com/canonical/iot-management: no Go files in /home/knitzsche/go/src/github.com/canonical/iot-management
$ cd go/src/github.com/canonical/iot-management/
$ ./get-deps.sh
bash: ./get-deps.sh: No such file or directory
$ find . -name get*
$ 
$ go build ./..
can't load package: package ./..: no Go files in /home/knitzsche/go/src/github.com/canonical
$

**Comment by dilyn-corner** [comment]
This should be fixed by Bugra's commit, so we can close I think.
